/*
 * TIMER1_INT.h
 *
 *  Created on: Oct 25, 2023
 *      Author: Ahmed Ehab
 */

#ifndef TIMER1_INT_H_
#define TIMER1_INT_H_

typedef enum{
	TIMER1_TCCR1A_e_WGM10,
	TIMER1_TCCR1A_e_WGM11,
	TIMER1_TCCR1A_e_FOC1B,
	TIMER1_TCCR1A_e_FOC1A,
	TIMER1_TCCR1A_e_COM1B0,
	TIMER1_TCCR1A_e_COM1B1,
	TIMER1_TCCR1A_e_COM1A0,
	TIMER1_TCCR1A_e_COM1A1
}TIMER1_TCCR1A_e;

typedef enum{
	TIMER1_TCCR1B_e_CS10,
	TIMER1_TCCR1B_e_CS11,
	TIMER1_TCCR1B_e_CS12,
	TIMER1_TCCR1B_e_WGM12,
	TIMER1_TCCR1B_e_WGM13,
	TIMER1_TCCR1B_e_RESERVED,
	TIMER1_TCCR1B_e_ICNC1,
	TIMER1_TCCR1B_e_ICES1
}TIMER1_TCCR1B_e;

typedef enum{
	TIMER1_TIMSK_e_TOIE1=2,
	TIMER1_TIMSK_e_OCIE1B,
	TIMER1_TIMSK_e_OCIE1A,
	TIMER1_TIMSK_e_TICIE1
}TIMER1_TIMSK_e;

typedef enum{
	TIMER1_TIFR_e_TOV1=2,
	TIMER1_TIFR_e_OCF1B,
	TIMER1_TIFR_e_OCF1A,
	TIMER1_TIFR_e_ICF1
}TIMER1_TIFR_e;

typedef enum{
	TIMER1_MODE_e_NORMAL,
	TIMER1_MODE_e_PWM_8bit,
	TIMER1_MODE_e_PWM_9bit,
	TIMER1_MODE_e_PWM_10bit,
	TIMER1_MODE_e_CTC_OCR1A,
	TIMER1_MODE_e_FAST_PWM_8bit,
	TIMER1_MODE_e_FAST_PWM_9bit,
	TIMER1_MODE_e_FAST_PWM_10bit,
	TIMER1_MODE_e_PWM_FREQUENCY_ICR1,
	TIMER1_MODE_e_PWM_FREQUENCY_OCR1A,
	TIMER1_MODE_e_PWM_ICR1,
	TIMER1_MODE_e_PWM_OCR1A,
	TIMER1_MODE_e_CTC_ICR1,
	TIMER1_MODE_e_RESERVED,
	TIMER1_MODE_e_FAST_PWM_ICR1,
	TIMER1_MODE_e_FAST_PWM_OCR1A
}TIMER1_MODE_e;

typedef enum{
	TIMER1_CLK_SELECT_e_NO_CLK,
	TIMER1_CLK_SELECT_e_NO_PRE,
	TIMER1_CLK_SELECT_e_PRE_8,
	TIMER1_CLK_SELECT_e_PRE_64,
	TIMER1_CLK_SELECT_e_PRE_256,
	TIMER1_CLK_SELECT_e_PRE_1024,
	TIMER1_CLK_SELECT_e_EXT_FALLING,
	TIMER1_CLK_SELECT_e_EXT_RISING,
}TIMER1_CLK_SELECT_e;

typedef enum
{
	TIMER1_NON_PWM_COMPARE_e_NORMAL,
	TIMER1_NON_PWM_COMPARE_e_TOGGLE_OC1A_OC1B,
	TIMER1_NON_PWM_COMPARE_e_CLEAR_OC1A_OC1B,
	TIMER1_NON_PWM_COMPARE_e_SET_OC1A_OC1B
}TIMER1_NON_PWM_COMPARE_e;

typedef enum
{
	TIMER1_PHASE_CORRECT_PWM_COMPARE_e_NORMAL,
	TIMER1_PHASE_CORRECT_PWM_COMPARE_e_TOGGLE_OC1A,
	TIMER1_PHASE_CORRECT_PWM_COMPARE_e_CLEAR_ON_UPCOUNTING,
	TIMER1_PHASE_CORRECT_PWM_COMPARE_e_SET_ON_UPCOUNTING
}TIMER1_PHASE_CORRECT_PWM_COMPARE_e;

typedef enum
{
	TIMER1_PHASE_FREQUENCY_CORRECT_PWM_COMPARE_e_NORMAL,
	TIMER1_PHASE_FREQUENCY_CORRECT_PWM_COMPARE_e_TOGGLE_OC1A,
	TIMER1_PHASE_FREQUENCY_CORRECT_PWM_COMPARE_e_CLEAR_ON_UPCOUNTING,
	TIMER1_PHASE_FREQUENCY_CORRECT_PWM_COMPARE_e_SET_ON_UPCOUNTING
}TIMER1_PHASE_FREQUENCY_CORRECT_PWM_COMPARE_e;

typedef enum
{
	TIMER1_FAST_PWM_COMPARE_e_NORMAL,
	TIMER1_FAST_PWM_COMPARE_e_TOGGLE_OC1A,
	TIMER1_FAST_PWM_COMPARE_e_CLEAR_OC1A_OC1B,
	TIMER1_FAST_PWM_COMPARE_e_SET_OC1A_OC1B
}TIMER1_FAST_PWM_COMPARE_e;

typedef enum
{
	TIMER1_CHANNEL_e_CHANNEL_A,
	TIMER1_CHANNEL_e_CHANNEL_B
}TIMER1_CHANNEL_e;
u8 TIMER1_u8Init(TIMER1_MODE_e TimerMode);
u8 TIMER1_u8ClkSelect(TIMER1_CLK_SELECT_e ClkSelect);
u8 TIMER1_vidSetPwmMode(TIMER1_PHASE_CORRECT_PWM_COMPARE_e PwmMode, TIMER1_CHANNEL_e Channel);
u8 TIMER1_vidSetFastPwmMode(TIMER1_FAST_PWM_COMPARE_e PwmMode, TIMER1_CHANNEL_e Channel);
u8 TIMER1_vidSetFreqPwmMode(TIMER1_PHASE_FREQUENCY_CORRECT_PWM_COMPARE_e PwmMode, TIMER1_CHANNEL_e Channel);
u8 TIMER1_vidSetNonPwmMode(TIMER1_NON_PWM_COMPARE_e PwmMode, TIMER1_CHANNEL_e Channel);
void TIMER1_vidStartTimer(void);
void TIMER1_vidStopTimer(void);
void TIMER1_vidSetPreload(u16 Copy_u16Preload);
void TIMER1_vidSetCTCA(u16 Copy_u16CTC);
void TIMER1_vidSetCTCB(u16 Copy_u16CTC);
void TIMER1_vidTovfInteruptEnable(void);
void TIMER1_vidTovfInteruptDisable(void);
void TIMER1_vidCtcAInteruptEnable(void);
void TIMER1_vidCtcAInteruptDisable(void);
void TIMER1_vidCtcBInteruptEnable(void);
void TIMER1_vidCtcBInteruptDisable(void);
void TIMER1_vidICRInteruptEnable(void);
void TIMER1_vidICRInteruptDisable(void);
void TIMER1_vidSetPwmADutyCycle(u16 Copy_u16DutyCycle);
void TIMER1_vidSetPwmBDutyCycle(u16 Copy_u16DutyCycle);
u8 TIMER1_u8SetOvfCbf(void(*fptr)(void));
u8 TIMER1_u8SetCtcACbf(void(*fptr)(void));
u8 TIMER1_u8SetCtcBCbf(void(*fptr)(void));
u8 TIMER1_u8SetICRCbf(void(*fptr)(void));
#endif /* TIMER1_INT_H_ */
