/*
 * TIMER2_INT.h
 *
 *  Created on: Oct 24, 2023
 *      Author: Ahmed Ehab
 */

#ifndef TIMER2_INT_H_
#define TIMER2_INT_H_

typedef enum
{
	TIMER2_TCCR2_e_CS20,
	TIMER2_TCCR2_e_CS21,
	TIMER2_TCCR2_e_CS22,
	TIMER2_TCCR2_e_WGM21,
	TIMER2_TCCR2_e_COM20,
	TIMER2_TCCR2_e_COM21,
	TIMER2_TCCR2_e_WGM20,
	TIMER2_TCCR2_e_FOC2
}TIMER2_TCCR2_e;

typedef enum
{
	TIMER2_ASSR_e_TCR2UB,
	TIMER2_ASSR_e_OCR2UB,
	TIMER2_ASSR_e_TCN2UB,
	TIMER2_ASSR_e_AS2,
}TIMER2_ASSR_e;

typedef enum
{
	TIMER2_TIMSK_e_TOIE2=6,
	TIMER2_TIMSK_e_OCIE2
}TIMER2_TIMSK_e;

typedef enum
{
	TIMER2_MODE_e_NORMAL,
	TIMER2_MODE_e_PWM,
	TIMER2_MODE_e_CTC,
	TIMER2_MODE_e_FAST_PWM
}TIMER2_MODE_e;

typedef enum
{
	TIMER2_PWM_COMPARE_e_NORMAL,
	TIMER2_PWM_COMPARE_e_TOGGLE_OC2,
	TIMER2_PWM_COMPARE_e_CLEAR_OC2,
	TIMER2_PWM_COMPARE_e_SET_OC2
}TIMER2_NON_PWM_COMPARE_e;

typedef enum
{
	TIMER2_PHASE_CORRECT_PWM_COMPARE_e_NORMAL,
	TIMER2_PHASE_CORRECT_PWM_COMPARE_e_TOGGLE_OC2,
	TIMER2_PHASE_CORRECT_PWM_COMPARE_e_CLEAR_ON_UPCOUNTING,
	TIMER2_PHASE_CORRECT_PWM_COMPARE_e_SET_ON_UPCOUNTING,
}TIMER2_PHASE_CORRECT_PWM_COMPARE_e;

typedef enum
{
	TIMER2_FAST_PWM_COMPARE_e_NORMAL,
	TIMER2_FAST_PWM_COMPARE_e_RESERVED,
	TIMER2_FAST_PWM_COMPARE_e_CLEAR_OC2,
	TIMER2_FAST_PWM_COMPARE_e_SET_OC2
}TIMER2_FAST_PWM_COMPARE_e;

typedef enum
{
	TIMER2_TIFR_e_TOV0,
	TIMER2_TIFR_e_OCF0
}TIMER2_TIFR_e;

typedef enum
{
	TIMER2_CLK_SELECT_e_NO_CLK,
	TIMER2_CLK_SELECT_e_NO_PRE,
	TIMER2_CLK_SELECT_e_PRE_8,
	TIMER2_CLK_SELECT_e_PRE_32,
	TIMER2_CLK_SELECT_e_PRE_64,
	TIMER2_CLK_SELECT_e_PRE_128,
	TIMER2_CLK_SELECT_e_PRE_256,
	TIMER2_CLK_SELECT_e_PRE_1024,
}TIMER2_CLK_SELECT_e;

typedef enum
{
	TIMER2_CLK_SRC_e_SYNC,
	TIMER2_CLK_SRC_e_ASYNC,
}TIMER2_CLK_SRC_e;

u8 TIMER2_u8Init(TIMER2_MODE_e TimerMode);
u8 TIMER2_u8ClkSelect(TIMER2_CLK_SRC_e ClkSrc,TIMER2_CLK_SELECT_e ClkSelect);
void TIMER2_vidStartTimer(void);
void TIMER2_vidStopTimer(void);
void TIMER2_vidSetPreload(u8 Copy_u8Preload);
void TIMER2_vidSetCTC(u8 Copy_u8CTC);
void TIMER2_vidTovfInteruptEnable(void);
void TIMER2_vidTovfInteruptDisable(void);
void TIMER2_vidCtcInteruptEnable(void);
void TIMER2_vidCtcInteruptDisable(void);
void TIMER2_vidSetPwmDutyCycle(u8 Copy_u8DutyCycle);
u8 TIMER2_u8SetOvfCbf(void(*fptr)(void));
u8 TIMER2_u8SetCtcCbf(void(*fptr)(void));
u8 TIMER2_u8SwitchSyncAndAsync();
#endif /* TIMER2_INT_H_ */
